### ISSUE TITLE
Code Organization

### ISSUE THREAD

**Issue by booleanhunter** [booleanhunter/ReactJS-AdminLTE#10]
This blog post talks about a good way to organize React code such as components and containers which could make the code base extremely modular - https://medium.com/@alexmngn/how-to-better-organize-your-react-applications-2fd3ea1920f1#.wgs3s0qen

The code base currently has duplicates existing in few places. These duplicates along with other boilerplate could be eliminated by following the guidelines mentioned in the blog.

**Comment by hassankhan** [comment]
One other thing might be to remove the `reactjs-adminlte` folder and move its child file/folders to the root directory.

**Comment by booleanhunter** [comment]
@hassankhan +1
