### ISSUE TITLE
npm repository

### ISSUE THREAD

**Issue by Mosho1** [booleanhunter/ReactJS-AdminLTE#11]
Since most react users use webpack and npm, it would be nice to have this up on npm.

**Comment by booleanhunter** [comment]
Thanks, this is a good suggestion! I'll set up an NPM repository soon.

**Comment by hassankhan** [comment]
All you need to do is sign into `npm` via command line if you already have an account on npmjs.org. Personally, I would prefer this to be a Yeoman generator package.

**Comment by booleanhunter** [comment]
Looks like the package name `reactjs-adminlte` is already taken!

**Comment by hassankhan** [comment]
Wicked, thanks!
