### ISSUE TITLE
Charts

### ISSUE THREAD

**Issue by DaFrik** [booleanhunter/ReactJS-AdminLTE#14]
Hi,

nice creation you have made there. I am looking for a reach driven dashboard, and i found yours! Just wonder hows the chart support in your creation? as I dont see any chart in the demo site and clicking in to the "chart" menu item give me a deadline :( 

Thanks!

**Comment by booleanhunter** [comment]
Were you looking for [this](http://ec2-52-74-208-196.ap-southeast-1.compute.amazonaws.com:8000) ?

I've still not finished the charts completely. And probably there will be changes to the few that's ready to use. But feel free to check them out in the meantime, you'll find them [here](https://github.com/booleanhunter/ReactJS-AdminLTE/tree/master/public/src/dashboardV1/js/components/charts). And you could refer this [file](https://github.com/booleanhunter/ReactJS-AdminLTE/blob/master/public/src/dashboardV1/js/components/dashboard.js) to understand how I've used them. I'll add the documentation soon!

**Comment by DaFrik** [comment]
@booleanhunter yes! your works are slick !

Thanks for the reply and pointers ! Keep up the good work :)

**Comment by booleanhunter** [comment]
@DaFrik - Thank you so much, glad to be of help!
