### ISSUE TITLE
webpack-dev-server + hot loader

### ISSUE THREAD

**Issue by pablotango** [booleanhunter/ReactJS-AdminLTE#15]
Great work man! 
just to know there are some missing lib (like webpack-raphael) when you try to run it with webpack-dev-server + hot loader.

then i cannot make it work correctly because when i run webpack-dev-server --hot --inline and i open http://localhost:8080/ the result is this: 

![Image of result](https://s32.postimg.org/tk10qtkol/Captura_de_pantalla_2016_07_12_a_las_22_58_07.png)

every html inside view i changed the path to contain correctly http://localhost:8080
what i'm doing wrong?

**Comment by nichesoftgh03** [comment]
1. In plugins of webpack.config.js: add "new webpack.HotModuleReplacementPlugin()"
2. In the end of server.js put following code:
"var webpack = require('webpack');
 var WebpackDevServer = require('webpack-dev-server');
 var config = require('./webpack.config');

 new WebpackDevServer(webpack(config), {
 	publicPath: config.output.publicPath,
 	hot: true,
 	historyApiFallback: true
 }).listen(8090, 'localhost', function (err, result) {
 	if (err) {
 		console.log(err);
 	}
	console.log('Listening at localhost:8090');
 });"

You are good to go now. In the command line just hit "node server.js" after webpack is done. Now hit buttons.html in views. Make sure the buttons.html has the bundled file and vendors served from "http://localhost:8090/".  Try rewriting some code and you can see the logs in the command prompt saying webpack is invalid and does webpack again and says that webpack is valid again. Now refresh the page. You can see the changes reflected.

**Comment by booleanhunter** [comment]
Thank you @nichesoftgh03, really appreciate the response!

**Comment by pablotango** [comment]
i'm sorry but... it didn't work for me... i will test again with a clean checkout, because i did some other test and maybe i've accidentally changed something else, because if i follow the steps written by @nichesoftgh03 the output is: "Cannot GET /"

**Comment by nichesoftgh03** [comment]
@pablotango , downloaded the project again and tried. It works perfect. Follow the first two steps. 

Then:
1. Go to buttons.html under views and replace 
<script src="dist/js/pages/dashboard.js"></script>
<script src="dist/js/demo.js"></script>

with 
<script src="http://localhost:8090/dist/js/vendors.js"></script>
<script src="http://localhost:8090/dist/js/buttons.bundle.js"></script>

2. Now go to public/src/buttons/js/components/buttons.js.
Remove the <HeaderBar />. When the webpack is valid refresh the page. This should work perfect. Have been working on this from past few weeks. Have done this twice. So, this should work. If it doesn't, please post the complete logs. Only then I can help you.

**Comment by pablotango** [comment]
Re-downloading from scratch: 

i will write you the exact steps i did:

git clone https://github.com/booleanhunter/ReactJS-AdminLTE.git AdminLTE
cd AdminLTE
npm install
npm install --only=dev
npm install webpack-raphael <<---- this is missing from packages.json
then in server.js i uncommented 

`var webpack = require('webpack');
 var WebpackDevServer = require('webpack-dev-server');
 var config = require('./webpack.config');

 new WebpackDevServer(webpack(config), {
 	publicPath: config.output.publicPath,
 	hot: true,
 	historyApiFallback: true
}).listen(8090, 'localhost', function (err, result) {
 	if (err) {
 		console.log(err);
 	}

   	console.log('Listening at localhost:8090');
 });
`

in webpack.config.js i decommented this:

`new webpack.HotModuleReplacementPlugin(),`

in buttons.html i changed the path:

`    <script src="http://localhost:8090/dist/js/vendors.js"></script>
    <script src="http://localhost:8090/dist/js/buttons.bundle.js"></script>
`

then i run node server.js after a while: 

Server listening at port 8000
Listening at localhost:8090
webpack: bundle is now VALID.

I load correctly the admin in http://localhost:8000/ and receive the log request to / received.

then everything i change did change nothing not hot reloading, no log in console.

**Comment by booleanhunter** [comment]
@pablotango Sorry for the late response.

I've added `webpack-raphael` to `package.json` now. would you try it out once again, following the exact same steps as those mentioned in the documentation?

**Comment by pablotango** [comment]
ok, now it works, even if the docs is not so clear.
just to know, locale for moment is breaking the flow, making the hot reload not working, 
to make it works i added in webpack.config.js this:

`        new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/), // to not to load all locales
`

**Comment by booleanhunter** [comment]
Great. Would you mind sharing with me how the docs could be improved further? You could make a P.R regarding the same and also for the hot reload issue, if you like! :smiley:
