### ISSUE TITLE
Cannot GET /documentation/index.html

### ISSUE THREAD

**Issue by gewentao** [booleanhunter/ReactJS-AdminLTE#19]
Hi,

It seems the document page can't be reached via 'http://localhost:8000/documentation/index.html'. Is there any other way to find some documents about how to use? 

Thanks,
Ted

**Comment by booleanhunter** [comment]
Hi,

If you want to see the documentation on how to use the widgets, you can refer the Readme files [here](https://github.com/booleanhunter/ReactJS-AdminLTE/tree/master/public/src/pages/widgets-page). It'll show you available widgets that you can use and how to configure them.

**Comment by gewentao** [comment]
Thanks~
